---
- name: Get all hosts in the same kafka group as current host
  ansible.builtin.set_fact:
    kafka_group_hosts: "{{ groups[item] | sort }}"
  loop: "{{ groups.keys() | list }}"
  when:
    - inventory_hostname in groups[item]
    - item is search('kafka')

- name: Create Kafka Broker group
  ansible.builtin.group:
    name: "{{ kafka_install.group }}"

- name: Create Kafka Broker user
  ansible.builtin.user:
    name: "{{ kafka_install.user }}"
    comment: Confluent Kafka
    system: true
    shell: "{{ kafka_install.user_login_shell }}"
    group: "{{ kafka_install.group }}"

- name: Install Java on Rhel
  ansible.builtin.dnf:
    name: "{{ kafka_install.rhl_java_package_name }}"
    state: present
  register: java_install_result
  until: java_install_result is success
  retries: 10
  delay: 5
  when:
    - ansible_os_family == "RedHat"

- name: Make sure confluent repo exists
  ansible.builtin.stat:
    path: /etc/yum.repos.d/confluent.repo
  register: confluent_yum_repo


- name: Add confluent yum repository on RedHat based distros
  when:
    - ansible_os_family == "RedHat"
    - kafka_install.method == "package"
    - not confluent_yum_repo.stat.exists
  block:
    - name: Render out confluent yum repository template
      ansible.builtin.template:
        src: "confluent.repo.j2"
        dest: "/etc/yum.repos.d/confluent.repo"
        owner: root
        group: root
        mode: "0644"
    - name: Update dnf cache to recognize confluent repository
      ansible.builtin.dnf:
        update_cache: true
