---
- name: Get all hosts in the same kafka group as current host
  ansible.builtin.set_fact:
    kafka_group_hosts: "{{ groups[item] | sort }}"
  loop: "{{ groups.keys() | list }}"
  when:
    - inventory_hostname in groups[item]
    - item is search('kafka')

- name: Create Kafka Broker group
  ansible.builtin.group:
    name: "{{ kafka_install.group }}"

- name: Create Kafka Broker user
  ansible.builtin.user:
    name: "{{ kafka_install.user }}"
    comment: Confluent Kafka
    system: true
    shell: "{{ kafka_install.user_login_shell }}"
    group: "{{ kafka_install.group }}"

- name: Install Java on Rhel
  ansible.builtin.dnf:
    name: "{{ kafka_install.rhl_java_package_name }}"
    state: present
  register: java_install_result
  until: java_install_result is success
  retries: 10
  delay: 5
  when:
    - ansible_os_family == "RedHat"
